preset: recommended

enabled:
  - concat_with_spaces
  - logical_not_operators_with_successor_space
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - concat_without_spaces
  - ordered_use
  - phpdoc_align
  - phpdoc_separation
  - phpdoc_short_description

linting: true

finder:
  exclude:
    - config
